### PR TITLE
agent: deserialize waitForPodDeletion check.

### LINKED ISSUE #149: CLUO uses pod name during deletion checks
The CLUO only checks the pod name for eviction checks. This is unsound, as pod names are not guaranteed to be unique or tied to a specific node.

https://github.com/coreos/container-linux-update-operator/blob/master/pkg/agent/agent.go#L362

It also serializes these checks for all pods where really they should be concurrent.

### PR DESCRIPTION
**Pull request by diegs**
This adds a sync.WaitGroup to check all pods concurrently and avoid
erroneously extended grace periods.

### CODE REVIEW

**Comment by dghubble** [comment]
Let's have the WaitGroups be separate and do the UID to continue mirroring upstream drain as in #151.

**Comment by diegs** [comment]
Ok, do you want me to scope this PR just to the waitgroup fix then?

**Comment by dghubble** [comment]
Sure

**Comment by diegs** [comment]
Rebased, though strictly not necessary since no conflicts... cc @euank :)

**Comment by euank** [comment]
Our repo allows merge commits. Was it indicating otherwise @dghubble?

**Comment by dghubble** [comment]
Habit, looks like its not enforced, which I'm fine with

**Pull request merged**
