### PR TITLE
pkg/agent: avoid exiting on watch termination

### PR DESCRIPTION
**Pull request by euank**
Works around #75. Properly, it would also distinguish between
"retryable" and "unretryable" errors, but client-go doesn't give us
great granularity.

In the future, adding further granularity would be a good idea.

This also tweaks whether delete failures are fatal based on a discussion @aaronlevy and I had a while ago.

cc @dghubble 

Testing done: none yet 😦

### CODE REVIEW

**Comment by aaronlevy** [comment]
LGTM assuming testing :)

**Comment by dghubble** [comment]
@euank did you push this anywhere already? We can manually test on a cluster, until #90 is addressed.

**Comment by dghubble** [comment]
quay.io/dghubble/container-linux-update-operator:f47bb6f82a7205f601064881492c97dbbb71afd9-dirty (dirty to fix the problems in the build scripts)

**Comment by dghubble** [comment]
I've tested this on a Kubernetes 1.6.4 cluster today (bare-metal, masked locksmithd) for both update-operator and update-agent. Tested fake D-bus signals and real update_engine updates from an older version of stable, no major regressions. I'll try to post something about this testing process soon, to formalize the process.

**Pull request merged**
