### PR TITLE
Release v0.6.0

### PR DESCRIPTION
**Pull request by dghubble**
Release notes:

* Add the `container-linux-update.v1.coreos.com/reboot-needed: "true"` label to reflect the "reboot-needed" annotation (#168)

### CODE REVIEW

**Comment by sdemos** [comment]
I don't feel strongly either way but does this warrant a full minor version release? especially so soon after the previous one. if you have a particular reason for it though, it seems fine to me.

**Comment by dghubble** [comment]
Yeah, I'm not so thrilled to have such a tiny release either. Its slightly more of a feature than a fix was my logic, but I could see either way.

**Comment by sdemos** [comment]
I guess since it does things like break the kvo when it tries to mess with our annotations, a minor version is probably warranted. let's just leave it as is.

**Comment by dghubble** [comment]
Yeah. And we'd wait for more features, but Tectonic seems to need this one.

**Pull request merged**
